### ISSUE TITLE
termbar can be moved / resized / maximized

### ISSUE THREAD

**Issue by peterwu** [gonzalo-/termbar#1]
Although termbar is positioned at the top of the screen, it can be moved or resized / maximized. Is there a way to fixate it at the top position? I've tried to use xprop to manipulate some parameters but no luck.

**Comment by gonzalo-** [comment]
Depends a lot on your wm, i never need this before and probably i will never use it this way, but you can play around with the "termbar" class geometry in your .Xresources, also keep in mind that termbar itself is just the output of a little program and what you need to resize or maximized is the xterm where termbar lives.

**Comment by peterwu** [comment]
Apparently, I'm on cwm. ;-)

The geometry parameter of xterm does position the bar at the right place initially but it can later be moved or resized.  

Anyway, I discovered that cwm has a window-freeze that can actually do what I am trying to do. But bar has to be created first and use key binding or mouse binding to freeze the window. 

After checking its source code, it seems cwm has defined its own **_CWM_WM_STATE_FREEZE** to handle this special case.
